import {MigrationInterface, QueryRunner} from "typeorm";

export class initial1647802892662 implements MigrationInterface {
    name = 'initial1647802892662'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "brand" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "image" character varying(255) NOT NULL, "createAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updateAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_5f468ae5696f07da025138e38f7" UNIQUE ("name"), CONSTRAINT "PK_a5d20765ddd942eb5de4eee2d7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "category_products" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "createAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updateAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_99f2d0af4214d8114f487923090" UNIQUE ("name"), CONSTRAINT "PK_f0ced3e957f2edbbc572b171686" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "description" text NOT NULL, "price" integer NOT NULL, "stock" integer NOT NULL, "image" character varying NOT NULL, "hub" character varying NOT NULL, "create_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "update_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "brand_id" integer, CONSTRAINT "UQ_4c9fb58de893725258746385e16" UNIQUE ("name"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_75895eeb1903f8a17816dafe0a" ON "products" ("price") `);
        await queryRunner.query(`CREATE INDEX "IDX_4fbc36ad745962e5c11001e1a8" ON "products" ("price", "stock") `);
        await queryRunner.query(`CREATE TABLE "order_item" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updateAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "quantity" integer NOT NULL, "productId" integer, "orderId" integer, CONSTRAINT "PK_d01158fe15b1ead5c26fd7f4e90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order" ("id" SERIAL NOT NULL, "createAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updateAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "customerId" integer, CONSTRAINT "PK_1031171c13130102495201e3e20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customer" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "lastName" character varying(255) NOT NULL, "document" character varying(255) NOT NULL, "gender" character varying(1) NOT NULL, "createAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updateAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a7a13f4cacb744524e44dfdad32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "role" character varying(100) NOT NULL, "createAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updateAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "customer_id" integer, CONSTRAINT "REL_d72eb2a5bbff4f2533a5d4caff" UNIQUE ("customer_id"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "taxonomy" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "createAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updateAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "publish" integer NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "UQ_4fdd8b92c2b4c3fa2825ce27b3d" UNIQUE ("name"), CONSTRAINT "PK_36dd19c538ef0f3d368a5ed1e09" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "term" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "description" text, "image" character varying(255), "copy" character varying(255), "createAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updateAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "publish" integer, "user_id" integer NOT NULL, "taxonomy_id" integer NOT NULL, CONSTRAINT "UQ_0283b849f99e4a232c0d04c8b8f" UNIQUE ("name"), CONSTRAINT "PK_55b0479f0743f2e5d5ec414821e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "content_type" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "create_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "update_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" integer NOT NULL, CONSTRAINT "PK_897d132e80d29e6a50e458f9b06" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comments" ("id" SERIAL NOT NULL, "value" text NOT NULL, "create_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "update_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" integer NOT NULL, CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "options" ("id" SERIAL NOT NULL, "value" text NOT NULL, "create_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "update_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d232045bdb5c14d932fba18d957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "questions" ("id" SERIAL NOT NULL, "description" text NOT NULL, "image" character varying(255), "create_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "update_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "option_id" integer, CONSTRAINT "PK_08a6d4b0f49ff300bf3a0ca60ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "nodes" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "description" text NOT NULL, "image" character varying(255), "url" character varying(255), "key" character varying NOT NULL, "publish" integer, "create_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "update_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" integer NOT NULL, "content_type_id" integer NOT NULL, CONSTRAINT "PK_682d6427523a0fa43d062ea03ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_359f55f7f8c42fd27b3e59e772" ON "nodes" ("title", "key") `);
        await queryRunner.query(`CREATE TABLE "documents" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "source" character varying(255) NOT NULL, "type" character varying(255) NOT NULL, "create_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "update_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" integer NOT NULL, CONSTRAINT "PK_ac51aa5181ee2036f5ca482857c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f5aa827a6a4f1f29940278412f" ON "documents" ("name") `);
        await queryRunner.query(`CREATE TABLE "field_brand" ("id" SERIAL NOT NULL, "create_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "update_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "node_id" integer NOT NULL, "term_id" integer NOT NULL, CONSTRAINT "PK_724c48c6615a004938eccfde637" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "node_fields" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "title" character varying(255), "type" character varying(255) NOT NULL, "createAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updateAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "entity_id" integer NOT NULL, CONSTRAINT "UQ_83546244fcb0aa6237e496958fb" UNIQUE ("name"), CONSTRAINT "PK_f4421e6f5900b702f40005191a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "node_fields_value" ("id" SERIAL NOT NULL, "value" text, "createAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updateAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "node_id" integer NOT NULL, "node_field_id" integer NOT NULL, CONSTRAINT "PK_89f9323f573acd18f42218bb588" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "trivia" ("id" SERIAL NOT NULL, "create_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "update_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" integer NOT NULL, "node_id" integer NOT NULL, CONSTRAINT "PK_faf9ea23fdea1723297b3e92c1a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "answers" ("id" SERIAL NOT NULL, "time" integer NOT NULL, "create_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "update_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "trivia_id" integer NOT NULL, "question_id" integer NOT NULL, "option_id" integer NOT NULL, CONSTRAINT "PK_9c32cec6c71e06da0254f2226c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "term_fields" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "title" character varying(255), "type" character varying(255) NOT NULL, "createAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updateAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "entity_id" integer NOT NULL, CONSTRAINT "UQ_3ca5a13d7fda3fb054df0c7002f" UNIQUE ("name"), CONSTRAINT "PK_dcebee1394fcf59e11bd6c2b90d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "term_fields_value" ("id" SERIAL NOT NULL, "value" text NOT NULL, "createAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updateAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "term_id" integer NOT NULL, "term_field_id" integer NOT NULL, CONSTRAINT "PK_f25b46813b044d1a2cfe73dbff6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tracking" ("id" SERIAL NOT NULL, "value" text, "time" integer, "entity_id" integer NOT NULL, "type" text NOT NULL, "create_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "update_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "term_id" integer, "brand_id" integer, "user_id" integer NOT NULL, "node_id" integer, CONSTRAINT "PK_c6d380f3abe9852840e5aff1439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "password_code" ("id" SERIAL NOT NULL, "code" character varying(255) NOT NULL, "publish" character varying DEFAULT '1', "createAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updateAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" integer NOT NULL, CONSTRAINT "PK_57ae77c51615068ed77aa79ddb5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products_categories" ("product_id" integer NOT NULL, "category_id" integer NOT NULL, CONSTRAINT "PK_634f5e1b5983772473fe0ec0008" PRIMARY KEY ("product_id", "category_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f2c76a4306a82c696d620f81f0" ON "products_categories" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_19fe0fe8c2fcf1cbe1a80f639f" ON "products_categories" ("category_id") `);
        await queryRunner.query(`CREATE TABLE "questions_options" ("question_id" integer NOT NULL, "option_id" integer NOT NULL, CONSTRAINT "PK_b4fd6fd825b5a45fc7e3bdbdcdd" PRIMARY KEY ("question_id", "option_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_abaa7fe0f2d7c3454469856fdf" ON "questions_options" ("question_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4dde0bbd49d894ca656192872d" ON "questions_options" ("option_id") `);
        await queryRunner.query(`CREATE TABLE "nodes_terms" ("node_id" integer NOT NULL, "term_id" integer NOT NULL, CONSTRAINT "PK_9adabe46360da53c66b8e86d198" PRIMARY KEY ("node_id", "term_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4ffc248120e20e9024a385697b" ON "nodes_terms" ("node_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_440c4533f76af92639fbf6f9c7" ON "nodes_terms" ("term_id") `);
        await queryRunner.query(`CREATE TABLE "nodes_documents" ("node_id" integer NOT NULL, "document_id" integer NOT NULL, CONSTRAINT "PK_a5c438df086bea2db93cf2112df" PRIMARY KEY ("node_id", "document_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_be2a11d8bdbf781f7a69355f4e" ON "nodes_documents" ("node_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb2a13bbbd9fb18d2e5dc4d2ba" ON "nodes_documents" ("document_id") `);
        await queryRunner.query(`CREATE TABLE "nodes_comments" ("node_id" integer NOT NULL, "comment_id" integer NOT NULL, CONSTRAINT "PK_2ae886e1281d398967b050cd7ae" PRIMARY KEY ("node_id", "comment_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0b2a59af95ef4d772d3f805aef" ON "nodes_comments" ("node_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c39ab7e5c79b7da63dd1246bc4" ON "nodes_comments" ("comment_id") `);
        await queryRunner.query(`CREATE TABLE "nodes_questions" ("node_id" integer NOT NULL, "question_id" integer NOT NULL, CONSTRAINT "PK_8f0d881b4b407ff77109350b91f" PRIMARY KEY ("node_id", "question_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_296da6b6755fe14dd06a757ae3" ON "nodes_questions" ("node_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f767f6193bbd2b2d9431109cd9" ON "nodes_questions" ("question_id") `);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_1530a6f15d3c79d1b70be98f2be" FOREIGN KEY ("brand_id") REFERENCES "brand"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_904370c093ceea4369659a3c810" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_646bf9ece6f45dbe41c203e06e0" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_124456e637cca7a415897dce659" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_d72eb2a5bbff4f2533a5d4caff9" FOREIGN KEY ("customer_id") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "taxonomy" ADD CONSTRAINT "FK_2e4c96c2b6c32cdad287b7d4176" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "term" ADD CONSTRAINT "FK_b1b2fc13bf4e852bb7b0e4d02ed" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "term" ADD CONSTRAINT "FK_d12e33ea8deecfec944ee3524db" FOREIGN KEY ("taxonomy_id") REFERENCES "taxonomy"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content_type" ADD CONSTRAINT "FK_025231abab44f9558a56152c2bb" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_4c675567d2a58f0b07cef09c13d" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_0bb75d7d78d1d21846deae55d88" FOREIGN KEY ("option_id") REFERENCES "options"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nodes" ADD CONSTRAINT "FK_a8e9d4a017a4c4ba2be64468e80" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nodes" ADD CONSTRAINT "FK_6bc23267032cd544573e6fcec23" FOREIGN KEY ("content_type_id") REFERENCES "content_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_c7481daf5059307842edef74d73" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "field_brand" ADD CONSTRAINT "FK_5887ceaf974567a188896bea3cd" FOREIGN KEY ("node_id") REFERENCES "nodes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "field_brand" ADD CONSTRAINT "FK_ac63d70d405a2f0a28fbe8e5cc1" FOREIGN KEY ("term_id") REFERENCES "term"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "node_fields" ADD CONSTRAINT "FK_832822111434284fbb659827f19" FOREIGN KEY ("entity_id") REFERENCES "content_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "node_fields_value" ADD CONSTRAINT "FK_b291106dd67b3fc1b3f29d5d9b8" FOREIGN KEY ("node_id") REFERENCES "nodes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "node_fields_value" ADD CONSTRAINT "FK_284da919cd996de6754a7cd770e" FOREIGN KEY ("node_field_id") REFERENCES "node_fields"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trivia" ADD CONSTRAINT "FK_2b5a8b27f3d089037c8170d1da5" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trivia" ADD CONSTRAINT "FK_e347d2b2643e6f58955e00d27de" FOREIGN KEY ("node_id") REFERENCES "nodes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_b66c79f0c63e89df6386068e6f9" FOREIGN KEY ("trivia_id") REFERENCES "trivia"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_677120094cf6d3f12df0b9dc5d3" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_67e979b8942acc80137116b6f12" FOREIGN KEY ("option_id") REFERENCES "options"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "term_fields" ADD CONSTRAINT "FK_9a23cac69d00f04e4a27abd9200" FOREIGN KEY ("entity_id") REFERENCES "taxonomy"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "term_fields_value" ADD CONSTRAINT "FK_7ef03fb71c3e9ab57eb9cff08a0" FOREIGN KEY ("term_id") REFERENCES "term"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "term_fields_value" ADD CONSTRAINT "FK_3e4befbb226c7a33434e599d2c8" FOREIGN KEY ("term_field_id") REFERENCES "term_fields"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracking" ADD CONSTRAINT "FK_c8f2010734eec81e729e22e7378" FOREIGN KEY ("term_id") REFERENCES "term"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracking" ADD CONSTRAINT "FK_cfa49e90637c0817f52ae5f2284" FOREIGN KEY ("brand_id") REFERENCES "term"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracking" ADD CONSTRAINT "FK_a2b147a66cbf2b142b5ed5d0b5f" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracking" ADD CONSTRAINT "FK_fe64b9a8732c96430d145885dcc" FOREIGN KEY ("node_id") REFERENCES "nodes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_code" ADD CONSTRAINT "FK_dc80bbbe8752f1e6e32f8e9ea20" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products_categories" ADD CONSTRAINT "FK_f2c76a4306a82c696d620f81f08" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "products_categories" ADD CONSTRAINT "FK_19fe0fe8c2fcf1cbe1a80f639f1" FOREIGN KEY ("category_id") REFERENCES "category_products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions_options" ADD CONSTRAINT "FK_abaa7fe0f2d7c3454469856fdf6" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "questions_options" ADD CONSTRAINT "FK_4dde0bbd49d894ca656192872d4" FOREIGN KEY ("option_id") REFERENCES "options"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nodes_terms" ADD CONSTRAINT "FK_4ffc248120e20e9024a385697ba" FOREIGN KEY ("node_id") REFERENCES "nodes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "nodes_terms" ADD CONSTRAINT "FK_440c4533f76af92639fbf6f9c7d" FOREIGN KEY ("term_id") REFERENCES "term"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nodes_documents" ADD CONSTRAINT "FK_be2a11d8bdbf781f7a69355f4e6" FOREIGN KEY ("node_id") REFERENCES "nodes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "nodes_documents" ADD CONSTRAINT "FK_cb2a13bbbd9fb18d2e5dc4d2ba3" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nodes_comments" ADD CONSTRAINT "FK_0b2a59af95ef4d772d3f805aef3" FOREIGN KEY ("node_id") REFERENCES "nodes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "nodes_comments" ADD CONSTRAINT "FK_c39ab7e5c79b7da63dd1246bc40" FOREIGN KEY ("comment_id") REFERENCES "comments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nodes_questions" ADD CONSTRAINT "FK_296da6b6755fe14dd06a757ae37" FOREIGN KEY ("node_id") REFERENCES "nodes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "nodes_questions" ADD CONSTRAINT "FK_f767f6193bbd2b2d9431109cd95" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "nodes_questions" DROP CONSTRAINT "FK_f767f6193bbd2b2d9431109cd95"`);
        await queryRunner.query(`ALTER TABLE "nodes_questions" DROP CONSTRAINT "FK_296da6b6755fe14dd06a757ae37"`);
        await queryRunner.query(`ALTER TABLE "nodes_comments" DROP CONSTRAINT "FK_c39ab7e5c79b7da63dd1246bc40"`);
        await queryRunner.query(`ALTER TABLE "nodes_comments" DROP CONSTRAINT "FK_0b2a59af95ef4d772d3f805aef3"`);
        await queryRunner.query(`ALTER TABLE "nodes_documents" DROP CONSTRAINT "FK_cb2a13bbbd9fb18d2e5dc4d2ba3"`);
        await queryRunner.query(`ALTER TABLE "nodes_documents" DROP CONSTRAINT "FK_be2a11d8bdbf781f7a69355f4e6"`);
        await queryRunner.query(`ALTER TABLE "nodes_terms" DROP CONSTRAINT "FK_440c4533f76af92639fbf6f9c7d"`);
        await queryRunner.query(`ALTER TABLE "nodes_terms" DROP CONSTRAINT "FK_4ffc248120e20e9024a385697ba"`);
        await queryRunner.query(`ALTER TABLE "questions_options" DROP CONSTRAINT "FK_4dde0bbd49d894ca656192872d4"`);
        await queryRunner.query(`ALTER TABLE "questions_options" DROP CONSTRAINT "FK_abaa7fe0f2d7c3454469856fdf6"`);
        await queryRunner.query(`ALTER TABLE "products_categories" DROP CONSTRAINT "FK_19fe0fe8c2fcf1cbe1a80f639f1"`);
        await queryRunner.query(`ALTER TABLE "products_categories" DROP CONSTRAINT "FK_f2c76a4306a82c696d620f81f08"`);
        await queryRunner.query(`ALTER TABLE "password_code" DROP CONSTRAINT "FK_dc80bbbe8752f1e6e32f8e9ea20"`);
        await queryRunner.query(`ALTER TABLE "tracking" DROP CONSTRAINT "FK_fe64b9a8732c96430d145885dcc"`);
        await queryRunner.query(`ALTER TABLE "tracking" DROP CONSTRAINT "FK_a2b147a66cbf2b142b5ed5d0b5f"`);
        await queryRunner.query(`ALTER TABLE "tracking" DROP CONSTRAINT "FK_cfa49e90637c0817f52ae5f2284"`);
        await queryRunner.query(`ALTER TABLE "tracking" DROP CONSTRAINT "FK_c8f2010734eec81e729e22e7378"`);
        await queryRunner.query(`ALTER TABLE "term_fields_value" DROP CONSTRAINT "FK_3e4befbb226c7a33434e599d2c8"`);
        await queryRunner.query(`ALTER TABLE "term_fields_value" DROP CONSTRAINT "FK_7ef03fb71c3e9ab57eb9cff08a0"`);
        await queryRunner.query(`ALTER TABLE "term_fields" DROP CONSTRAINT "FK_9a23cac69d00f04e4a27abd9200"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "FK_67e979b8942acc80137116b6f12"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "FK_677120094cf6d3f12df0b9dc5d3"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "FK_b66c79f0c63e89df6386068e6f9"`);
        await queryRunner.query(`ALTER TABLE "trivia" DROP CONSTRAINT "FK_e347d2b2643e6f58955e00d27de"`);
        await queryRunner.query(`ALTER TABLE "trivia" DROP CONSTRAINT "FK_2b5a8b27f3d089037c8170d1da5"`);
        await queryRunner.query(`ALTER TABLE "node_fields_value" DROP CONSTRAINT "FK_284da919cd996de6754a7cd770e"`);
        await queryRunner.query(`ALTER TABLE "node_fields_value" DROP CONSTRAINT "FK_b291106dd67b3fc1b3f29d5d9b8"`);
        await queryRunner.query(`ALTER TABLE "node_fields" DROP CONSTRAINT "FK_832822111434284fbb659827f19"`);
        await queryRunner.query(`ALTER TABLE "field_brand" DROP CONSTRAINT "FK_ac63d70d405a2f0a28fbe8e5cc1"`);
        await queryRunner.query(`ALTER TABLE "field_brand" DROP CONSTRAINT "FK_5887ceaf974567a188896bea3cd"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_c7481daf5059307842edef74d73"`);
        await queryRunner.query(`ALTER TABLE "nodes" DROP CONSTRAINT "FK_6bc23267032cd544573e6fcec23"`);
        await queryRunner.query(`ALTER TABLE "nodes" DROP CONSTRAINT "FK_a8e9d4a017a4c4ba2be64468e80"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "FK_0bb75d7d78d1d21846deae55d88"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_4c675567d2a58f0b07cef09c13d"`);
        await queryRunner.query(`ALTER TABLE "content_type" DROP CONSTRAINT "FK_025231abab44f9558a56152c2bb"`);
        await queryRunner.query(`ALTER TABLE "term" DROP CONSTRAINT "FK_d12e33ea8deecfec944ee3524db"`);
        await queryRunner.query(`ALTER TABLE "term" DROP CONSTRAINT "FK_b1b2fc13bf4e852bb7b0e4d02ed"`);
        await queryRunner.query(`ALTER TABLE "taxonomy" DROP CONSTRAINT "FK_2e4c96c2b6c32cdad287b7d4176"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_d72eb2a5bbff4f2533a5d4caff9"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_124456e637cca7a415897dce659"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_646bf9ece6f45dbe41c203e06e0"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_904370c093ceea4369659a3c810"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_1530a6f15d3c79d1b70be98f2be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f767f6193bbd2b2d9431109cd9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_296da6b6755fe14dd06a757ae3"`);
        await queryRunner.query(`DROP TABLE "nodes_questions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c39ab7e5c79b7da63dd1246bc4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b2a59af95ef4d772d3f805aef"`);
        await queryRunner.query(`DROP TABLE "nodes_comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb2a13bbbd9fb18d2e5dc4d2ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be2a11d8bdbf781f7a69355f4e"`);
        await queryRunner.query(`DROP TABLE "nodes_documents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_440c4533f76af92639fbf6f9c7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ffc248120e20e9024a385697b"`);
        await queryRunner.query(`DROP TABLE "nodes_terms"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4dde0bbd49d894ca656192872d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abaa7fe0f2d7c3454469856fdf"`);
        await queryRunner.query(`DROP TABLE "questions_options"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19fe0fe8c2fcf1cbe1a80f639f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2c76a4306a82c696d620f81f0"`);
        await queryRunner.query(`DROP TABLE "products_categories"`);
        await queryRunner.query(`DROP TABLE "password_code"`);
        await queryRunner.query(`DROP TABLE "tracking"`);
        await queryRunner.query(`DROP TABLE "term_fields_value"`);
        await queryRunner.query(`DROP TABLE "term_fields"`);
        await queryRunner.query(`DROP TABLE "answers"`);
        await queryRunner.query(`DROP TABLE "trivia"`);
        await queryRunner.query(`DROP TABLE "node_fields_value"`);
        await queryRunner.query(`DROP TABLE "node_fields"`);
        await queryRunner.query(`DROP TABLE "field_brand"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f5aa827a6a4f1f29940278412f"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_359f55f7f8c42fd27b3e59e772"`);
        await queryRunner.query(`DROP TABLE "nodes"`);
        await queryRunner.query(`DROP TABLE "questions"`);
        await queryRunner.query(`DROP TABLE "options"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP TABLE "content_type"`);
        await queryRunner.query(`DROP TABLE "term"`);
        await queryRunner.query(`DROP TABLE "taxonomy"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "customer"`);
        await queryRunner.query(`DROP TABLE "order"`);
        await queryRunner.query(`DROP TABLE "order_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4fbc36ad745962e5c11001e1a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75895eeb1903f8a17816dafe0a"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "category_products"`);
        await queryRunner.query(`DROP TABLE "brand"`);
    }

}
